services:
  mysqldb:
    image: mysql:latest
    restart: always
    container_name: "mysqldb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: taskdb
      MYSQL_ROOT_PASSWORD: secret
    #    volumes:
    #      - C:/data/mysql:/var/lib/mysql
    networks:
      - data3
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost || exit 1" ]
      timeout: 20s
      retries: 10

  webapi:
#    image: behnamghafouri/spring-oauth-server-image
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "springapi"
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - data3

networks:
  data3:
    external: true